# Generated by Django 3.2.13 on 2022-12-05 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_userpost_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='location',
            field=models.TextField(default='STRING'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 19, 26, 47, 168084, tzinfo=utc)),
        ),
    ]
