# Generated by Django 3.2.13 on 2022-12-07 01:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20221207_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 1, 1, 15, 951881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 1, 1, 15, 951908, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=25)),
                ('deadline', models.DateField(default=datetime.datetime(2022, 12, 7, 1, 1, 15, 953301, tzinfo=utc))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_post', to='jobs.userpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
