# Generated by Django 3.2.13 on 2022-12-05 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20221205_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 19, 39, 8, 280731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship')], default='Ex: Part Time', max_length=20),
        ),
    ]
