# Generated by Django 3.2.13 on 2022-12-05 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20221205_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='preferred_skills',
            field=models.CharField(default='Ex: Python, Java', max_length=500),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 19, 41, 26, 483209, tzinfo=utc)),
        ),
    ]
