# Generated by Django 3.2.13 on 2022-12-07 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20221207_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 18, 50, 11, 38298, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 18, 50, 11, 36842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 18, 50, 11, 36873, tzinfo=utc)),
        ),
    ]
