# Generated by Django 3.2.13 on 2022-12-07 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20221207_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='url',
            field=models.SlugField(blank=True, editable=False, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 19, 28, 18, 927949, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 19, 28, 18, 926602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 19, 28, 18, 926634, tzinfo=utc)),
        ),
    ]
