# Generated by Django 3.2.13 on 2022-12-05 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20221205_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 19, 59, 1, 506677, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 19, 59, 1, 506707, tzinfo=utc)),
        ),
    ]
