# Generated by Django 3.2.13 on 2022-12-05 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20221205_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='location',
        ),
        migrations.AddField(
            model_name='userpost',
            name='city',
            field=models.CharField(default='Ex: Cincinnati', max_length=50),
        ),
        migrations.AddField(
            model_name='userpost',
            name='state',
            field=models.CharField(default='Ex: Ohio', max_length=50),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 20, 3, 19, 853340, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 20, 3, 19, 853387, tzinfo=utc)),
        ),
    ]
