# Generated by Django 3.2.13 on 2022-12-08 02:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20221208_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 12, 8, 2, 55, 4, 61891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 2, 55, 4, 60416, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 2, 55, 4, 60446, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
