# Generated by Django 3.2.13 on 2022-12-08 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20221208_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 12, 8, 3, 0, 6, 209671, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 3, 0, 6, 208318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 3, 0, 6, 208347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='preferred_skills',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50),
        ),
    ]
