# Generated by Django 3.2.13 on 2022-12-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20221207_1850'),
        ('jobs', '0015_auto_20221208_0300'),
    ]

    operations = [
    ]
