# Generated by Django 3.2.13 on 2022-12-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_merge_0008_auto_20221207_1850_0015_auto_20221208_0300'),
        ('jobs', '0019_auto_20221208_1844'),
    ]

    operations = [
    ]
